spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://localhost:5432/ticket_booking
    username: admin
    password: secret
    driver-class-name: org.postgresql.Driver
  data:
    mongodb:
      uri: mongodb://localhost:27017/
      database: ticket_booking

logging:
  level:
    org:
      hibernate:
        SQL: debug
        type: trace
    net:
      sf:
        ehcache=debug: